--- #YAML:1.0
name:               Net-Amazon-AWSSign
version:            0.09
abstract:           Perl extension to create signatures for AWS requests
author:
    - Naton Aiman-Smith <naton@>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::SHA:   0
    MIME::Base64:  0
    URI::Escape:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
