--- #YAML:1.0
name:                Net-Amazon-AWSSign
version:             0.06
abstract:            Perl extension to create signatures for AWS requests
license:             ~
author:              
    - Naton Aiman-Smith <naton@>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Digest::SHA:                   0
    MIME::Base64:                  0
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
